name: test

services:

  front:
    build:
      dockerfile_inline: |
        FROM nginx:latest
        RUN apt update
        RUN apt install net-tools iputils-ping wget -y
    hostname: front
    ports:
      - 80:80

  api:
    build:
      dockerfile_inline: |
        FROM nginx:latest
        RUN apt update
        RUN apt install net-tools iputils-ping wget -y
    hostname: api
    deploy:
      replicas: 3

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=123321

networks:
  
  default:
    enable_ipv4: true
    enable_ipv6: false