name: store

services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: store
      POSTGRES_PASSWORD: store
      POSTGRES_DB: store
  
  account:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_DB: store
      DATABASE_USERNAME: store
      DATABASE_PASSWORD: store
    # ports:
    #   - "8080:8080"
    deploy:
      replicas: 2

  gateway:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

